# ==========================================
# 宏文件：运行 662 keV 伽马源，200,000 事例
# ==========================================

# 1. 关闭终端刷屏
/tracking/verbose 0
/run/verbose 0

# 2. 初始化内核
/run/initialize

# 3. 设置粒子源
/gps/particle gamma
/gps/energy 662 keV
/gps/position 0 0 -5 cm
/gps/direction 0 0 1

# 上半球各向同性发射
#/gps/pos/type Point
#/gps/pos/centre 0 0 -10 cm
#/gps/ang/type iso
#/gps/ang/mintheta 0.0 deg
#/gps/ang/maxtheta 90.0 deg

# 4. 运行事例
/run/beamOn 200000